spring:
  cloud:
    gcp:
      credentials:
        location: tasvirni-matnga-0a2004b8f49c.json
  datasource:
    password: 123
    username: ahrorjon
    url: jdbc:postgresql://localhost:5432/tasvirni_matnga
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#logging:
#  level:
#    org:
#      zalando:
#        logback: